#!/usr/bin/bash

( [ ! -f symb.o ] \
  || [ symb.cc -nt symb.o ] \
  || [ symb.h -nt symb.o ] ) && \
  clang++ -o symb.o -c symb.cc -O3 -std=c++20

( [ ! -f integ ] \
  || [ main.cc -nt integ ] \
  || [ symb.o -nt integ ] ) && \
  clang++ -o integ main.cc symb.o -O3 -std=c++20
